name: 'Excalidraw Render Action'
description: 'Convert Excalidraw files to PNG images'
branding:
  icon: 'image'
  color: 'purple'

inputs:
  input-dir:
    description: 'Directory containing .excalidraw files'
    required: false
    default: '.'
  output-dir:
    description: 'Directory to output PNG files (defaults to same as input directory)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install excalidraw-cli
      shell: bash
      run: npm install -g @tommywalkie/excalidraw-cli
    
    - name: Convert Excalidraw files to PNG
      shell: bash
      run: |
        INPUT_DIR="${{ inputs.input-dir }}"
        OUTPUT_DIR="${{ inputs.output-dir }}"
        
        if [ -z "$OUTPUT_DIR" ]; then
          OUTPUT_DIR="$INPUT_DIR"
        fi
        
        INPUT_DIR=$(realpath "$INPUT_DIR")
        OUTPUT_DIR=$(realpath "$OUTPUT_DIR")
        
        echo "Searching for .excalidraw files in: $INPUT_DIR"
        echo "Output directory: $OUTPUT_DIR"
        
        found_files=0
        while IFS= read -r -d '' file; do
          found_files=$((found_files + 1))
          filename=$(basename "$file" .excalidraw)
          file_dir=$(dirname "$file")
          
          if [ "$file_dir" = "$INPUT_DIR" ]; then
            output_path="$OUTPUT_DIR"
          else
            relative_dir="${file_dir#$INPUT_DIR/}"
            output_path="$OUTPUT_DIR/$relative_dir"
          fi
          
          mkdir -p "$output_path"
          
          echo "Converting $file to $output_path/${filename}.png"
          excalidraw-cli "$file" -o "$output_path" -f png
        done < <(find "$INPUT_DIR" -name "*.excalidraw" -type f -print0)
        
        if [ $found_files -eq 0 ]; then
          echo "Warning: No .excalidraw files found in $INPUT_DIR"
        else
          echo "Successfully converted $found_files file(s)"
        fi
